begin;

update public.tenants
set name = 'Solesneakers'
where name = 'Realdealkickzsc'
  and not exists (select 1 from public.tenants where name = 'Solesneakers');

insert into public.tenants (name)
select 'Solesneakers'
where not exists (select 1 from public.tenants where name = 'Solesneakers');

insert into public.tag_brands (tenant_id, canonical_label, is_active)
select null, seed.label, seed.is_active
from (values
    ('A Bathing Ape', true),
    ('Adidas', true),
    ('Air Jordan', true),
    ('Alexander McQueen', true),
    ('Amiri', true),
    ('ASICS', true),
    ('Balenciaga', true),
    ('Bottega Desires', true),
    ('Bravest Studios', true),
    ('Burberry', true),
    ('Chanel', true),
    ('Chrome Hearts', true),
    ('Denim Tears', true),
    ('Dior', true),
    ('Distant Studios', true),
    ('Dolce and Gabbana', true),
    ('Essentials Fear of God', true),
    ('Gallery Dept.', true),
    ('Godspeed', true),
    ('Gucci', true),
    ('GV Gallery', true),
    ('GW', true),
    ('Hellstar', true),
    ('Lanvin', true),
    ('Louis Vuitton', true),
    ('Maison Margiela', true),
    ('Maison Mihara Yasuhiro', true),
    ('Marni', true),
    ('Mes Amis', true),
    ('New Balance', true),
    ('Nike', true),
    ('Off-White', true),
    ('Other', true),
    ('Palm Angels', true),
    ('Prada', true),
    ('Prestige', true),
    ('RetroVert', true),
    ('Rick Owens', true),
    ('Righteous', true),
    ('Saint Vanity', true),
    ('Sp5der', true),
    ('Supreme', true),
    ('Timberland', true),
    ('Vale', true),
    ('Vans', true),
    ('Versace', true)
) as seed(label, is_active)
where not exists (
  select 1 from public.tag_brands b
  where b.tenant_id is null and lower(b.canonical_label) = lower(seed.label)
);

insert into public.tag_models (tenant_id, brand_id, canonical_label, is_active)
select null, brand.id, seed.model_label, seed.is_active
from (values
    ('A Bathing Ape', 'BAPE SK8', true),
    ('A Bathing Ape', 'BAPE STA', true),
    ('Adidas', 'Yeezy 350', true),
    ('Adidas', 'Yeezy 380', true),
    ('Adidas', 'Yeezy 500', true),
    ('Adidas', 'Yeezy 700', true),
    ('Adidas', 'Yeezy 700 V2', true),
    ('Adidas', 'Yeezy 700 V3', true),
    ('Adidas', 'Yeezy Desert Boot', true),
    ('Adidas', 'Yeezy Foam Runner', true),
    ('Air Jordan', '1', true),
    ('Air Jordan', '10', true),
    ('Air Jordan', '11', true),
    ('Air Jordan', '12', true),
    ('Air Jordan', '13', true),
    ('Air Jordan', '14', true),
    ('Air Jordan', '15', true),
    ('Air Jordan', '16', true),
    ('Air Jordan', '17', true),
    ('Air Jordan', '18', true),
    ('Air Jordan', '19', true),
    ('Air Jordan', '2', true),
    ('Air Jordan', '20', true),
    ('Air Jordan', '21', true),
    ('Air Jordan', '22', true),
    ('Air Jordan', '23', true),
    ('Air Jordan', '24', true),
    ('Air Jordan', '25', true),
    ('Air Jordan', '26', true),
    ('Air Jordan', '27', true),
    ('Air Jordan', '28', true),
    ('Air Jordan', '29', true),
    ('Air Jordan', '3', true),
    ('Air Jordan', '30', true),
    ('Air Jordan', '31', true),
    ('Air Jordan', '32', true),
    ('Air Jordan', '33', true),
    ('Air Jordan', '34', true),
    ('Air Jordan', '35', true),
    ('Air Jordan', '36', true),
    ('Air Jordan', '37', true),
    ('Air Jordan', '38', true),
    ('Air Jordan', '39', true),
    ('Air Jordan', '4', true),
    ('Air Jordan', '40', true),
    ('Air Jordan', '5', true),
    ('Air Jordan', '6', true),
    ('Air Jordan', '7', true),
    ('Air Jordan', '8', true),
    ('Air Jordan', '9', true),
    ('Alexander McQueen', 'Oversized', true),
    ('Amiri', 'Arigato', true),
    ('Amiri', 'Classic', true),
    ('Amiri', 'Skel', true),
    ('ASICS', 'GEL-1130', true),
    ('ASICS', 'GEL-DS Trainer', true),
    ('ASICS', 'GEL-K1011', true),
    ('ASICS', 'GEL-Kayano 14', true),
    ('ASICS', 'GEL-Lyte III', true),
    ('ASICS', 'GEL-NYC', true),
    ('ASICS', 'GT-2160', true),
    ('Balenciaga', '3XL', true),
    ('Balenciaga', 'Defender', true),
    ('Balenciaga', 'Runner', true),
    ('Balenciaga', 'Track', true),
    ('Balenciaga', 'Triple S', true),
    ('Bravest Studios', 'Claw Mules', true),
    ('Burberry', 'Union Check', true),
    ('Dior', 'B22', true),
    ('Dior', 'B23', true),
    ('Dolce and Gabbana', 'Stretch Mesh Fast Sneaker', true),
    ('Gucci', 'Ace', true),
    ('Gucci', 'GG Supreme', true),
    ('Gucci', 'Rhyton', true),
    ('Gucci', 'Tennis 1977', true),
    ('Lanvin', 'Curb', true),
    ('Louis Vuitton', 'Run Away', true),
    ('Louis Vuitton', 'Skate', true),
    ('Louis Vuitton', 'Trainer', true),
    ('Maison Margiela', 'Replica', true),
    ('Maison Mihara Yasuhiro', 'Baker', true),
    ('Maison Mihara Yasuhiro', 'Charles', true),
    ('Maison Mihara Yasuhiro', 'Hank', true),
    ('Maison Mihara Yasuhiro', 'Parker', true),
    ('Maison Mihara Yasuhiro', 'Peterson', true),
    ('Maison Mihara Yasuhiro', 'Wayne', true),
    ('Marni', 'Pablo', true),
    ('New Balance', '1906R', true),
    ('New Balance', '327', true),
    ('New Balance', '550', true),
    ('New Balance', '9060', true),
    ('New Balance', '990v3', true),
    ('New Balance', '990v6', true),
    ('New Balance', '991', true),
    ('Nike', 'Air DT Max', true),
    ('Nike', 'Air Foamposite', true),
    ('Nike', 'Air Force 1', true),
    ('Nike', 'Air Max 1', true),
    ('Nike', 'Air Max 97', true),
    ('Nike', 'Air Max Plus', true),
    ('Nike', 'Air More Uptempo', true),
    ('Nike', 'AIR ZOOM FLIGHT 95', true),
    ('Nike', 'Blazer', true),
    ('Nike', 'Dunk Low', true),
    ('Nike', 'KD', true),
    ('Nike', 'Kobe', true),
    ('Nike', 'LeBron', true),
    ('Nike', 'P-6000', true),
    ('Nike', 'SB Dunk High', true),
    ('Nike', 'SB Dunk Low', true),
    ('Nike', 'Vomero 5', true),
    ('Off-White', 'Out Of Office', true),
    ('Off-White', 'Vulcanized', true),
    ('Palm Angels', 'Ramones', true),
    ('Prada', 'Americas Cup', true),
    ('Prada', 'Cloudbust Thunder', true),
    ('Rick Owens', 'Geobasket', true),
    ('Rick Owens', 'Geth Runner', true),
    ('Timberland', 'Authentic 3-Eye Lug Boat Shoe', true),
    ('Timberland', 'Euro Hiker', true),
    ('Timberland', 'Field Boot', true),
    ('Timberland', 'Premium 6-Inch Waterproof Boot', true),
    ('Vans', 'Old Skool', true),
    ('Versace', 'Chain Reaction', true)
) as seed(brand_label, model_label, is_active)
join public.tag_brands brand
  on brand.tenant_id is null and lower(brand.canonical_label) = lower(seed.brand_label)
where not exists (
  select 1 from public.tag_models model
  where model.brand_id = brand.id
    and model.tenant_id is null
    and lower(model.canonical_label) = lower(seed.model_label)
);

insert into public.tag_aliases (
  tenant_id, entity_type, brand_id, alias_label, alias_normalized, priority, is_active
)
select null, 'brand', brand.id, seed.alias_label, seed.alias_normalized, seed.priority, seed.is_active
from (values
    ('A Bathing Ape', 'A Bathing Ape', 'a bathing ape', 5, true),
    ('A Bathing Ape', 'BAPE', 'bape', 10, true),
    ('A Bathing Ape', 'Bathing Ape', 'bathing ape', 5, true),
    ('Air Jordan', 'Jordan', 'jordan', 1, true),
    ('Distant Studios', 'Distant', 'distant', 1, true),
    ('Maison Mihara Yasuhiro', 'Maison Mihara', 'maison mihara', 5, true),
    ('New Balance', 'NB', 'nb', 10, true),
    ('Rick Owens', 'Rich Owens', 'rich owens', 1, true),
    ('Timberland', 'Timberlands', 'timberlands', 1, true)
) as seed(brand_label, alias_label, alias_normalized, priority, is_active)
join public.tag_brands brand
  on brand.tenant_id is null and lower(brand.canonical_label) = lower(seed.brand_label)
where not exists (
  select 1 from public.tag_aliases alias
  where alias.tenant_id is null
    and alias.entity_type = 'brand'
    and alias.alias_normalized = seed.alias_normalized
);

insert into public.tag_aliases (
  tenant_id, entity_type, model_id, alias_label, alias_normalized, priority, is_active
)
select null, 'model', model.id, seed.alias_label, seed.alias_normalized, seed.priority, seed.is_active
from (values
    ('A Bathing Ape', 'BAPE STA', 'BAPE STA', 'bape sta', 8, true),
    ('A Bathing Ape', 'BAPE STA', 'BAPE STA™', 'bape sta ', 6, true),
    ('A Bathing Ape', 'BAPE STA', 'BAPESTA', 'bapesta', 10, true),
    ('Air Jordan', '1', 'Air Jordan 1', 'air jordan 1', 1, true),
    ('Air Jordan', '1', 'AJ1', 'aj1', 1, true),
    ('Air Jordan', '1', 'Jordan 1', 'jordan 1', 1, true),
    ('Air Jordan', '1', 'Jordan I', 'jordan i', 1, true),
    ('Air Jordan', '10', 'Air Jordan 10', 'air jordan 10', 1, true),
    ('Air Jordan', '10', 'AJ10', 'aj10', 1, true),
    ('Air Jordan', '10', 'Jordan 10', 'jordan 10', 1, true),
    ('Air Jordan', '10', 'Jordan X', 'jordan x', 1, true),
    ('Air Jordan', '11', 'Air Jordan 11', 'air jordan 11', 1, true),
    ('Air Jordan', '11', 'AJ11', 'aj11', 1, true),
    ('Air Jordan', '11', 'Jordan 11', 'jordan 11', 1, true),
    ('Air Jordan', '11', 'Jordan XI', 'jordan xi', 1, true),
    ('Air Jordan', '12', 'Air Jordan 12', 'air jordan 12', 1, true),
    ('Air Jordan', '12', 'AJ12', 'aj12', 1, true),
    ('Air Jordan', '12', 'Jordan 12', 'jordan 12', 1, true),
    ('Air Jordan', '12', 'Jordan XII', 'jordan xii', 1, true),
    ('Air Jordan', '13', 'Air Jordan 13', 'air jordan 13', 1, true),
    ('Air Jordan', '13', 'AJ13', 'aj13', 1, true),
    ('Air Jordan', '13', 'Jordan 13', 'jordan 13', 1, true),
    ('Air Jordan', '13', 'Jordan XIII', 'jordan xiii', 1, true),
    ('Air Jordan', '14', 'Air Jordan 14', 'air jordan 14', 1, true),
    ('Air Jordan', '14', 'AJ14', 'aj14', 1, true),
    ('Air Jordan', '14', 'Jordan 14', 'jordan 14', 1, true),
    ('Air Jordan', '14', 'Jordan XIV', 'jordan xiv', 1, true),
    ('Air Jordan', '15', 'Air Jordan 15', 'air jordan 15', 1, true),
    ('Air Jordan', '15', 'AJ15', 'aj15', 1, true),
    ('Air Jordan', '15', 'Jordan 15', 'jordan 15', 1, true),
    ('Air Jordan', '15', 'Jordan XV', 'jordan xv', 1, true),
    ('Air Jordan', '16', 'Air Jordan 16', 'air jordan 16', 1, true),
    ('Air Jordan', '16', 'AJ16', 'aj16', 1, true),
    ('Air Jordan', '16', 'Jordan 16', 'jordan 16', 1, true),
    ('Air Jordan', '16', 'Jordan XVI', 'jordan xvi', 1, true),
    ('Air Jordan', '17', 'Air Jordan 17', 'air jordan 17', 1, true),
    ('Air Jordan', '17', 'AJ17', 'aj17', 1, true),
    ('Air Jordan', '17', 'Jordan 17', 'jordan 17', 1, true),
    ('Air Jordan', '17', 'Jordan XVII', 'jordan xvii', 1, true),
    ('Air Jordan', '18', 'Air Jordan 18', 'air jordan 18', 1, true),
    ('Air Jordan', '18', 'AJ18', 'aj18', 1, true),
    ('Air Jordan', '18', 'Jordan 18', 'jordan 18', 1, true),
    ('Air Jordan', '18', 'Jordan XVIII', 'jordan xviii', 1, true),
    ('Air Jordan', '19', 'Air Jordan 19', 'air jordan 19', 1, true),
    ('Air Jordan', '19', 'AJ19', 'aj19', 1, true),
    ('Air Jordan', '19', 'Jordan 19', 'jordan 19', 1, true),
    ('Air Jordan', '19', 'Jordan XIX', 'jordan xix', 1, true),
    ('Air Jordan', '2', 'Air Jordan 2', 'air jordan 2', 1, true),
    ('Air Jordan', '2', 'AJ2', 'aj2', 1, true),
    ('Air Jordan', '2', 'Jordan 2', 'jordan 2', 1, true),
    ('Air Jordan', '2', 'Jordan II', 'jordan ii', 1, true),
    ('Air Jordan', '20', 'Air Jordan 20', 'air jordan 20', 1, true),
    ('Air Jordan', '20', 'AJ20', 'aj20', 1, true),
    ('Air Jordan', '20', 'Jordan 20', 'jordan 20', 1, true),
    ('Air Jordan', '20', 'Jordan XX', 'jordan xx', 1, true),
    ('Air Jordan', '21', 'Air Jordan 21', 'air jordan 21', 1, true),
    ('Air Jordan', '21', 'AJ21', 'aj21', 1, true),
    ('Air Jordan', '21', 'Jordan 21', 'jordan 21', 1, true),
    ('Air Jordan', '21', 'Jordan XXI', 'jordan xxi', 1, true),
    ('Air Jordan', '22', 'Air Jordan 22', 'air jordan 22', 1, true),
    ('Air Jordan', '22', 'AJ22', 'aj22', 1, true),
    ('Air Jordan', '22', 'Jordan 22', 'jordan 22', 1, true),
    ('Air Jordan', '22', 'Jordan XXII', 'jordan xxii', 1, true),
    ('Air Jordan', '23', 'Air Jordan 23', 'air jordan 23', 1, true),
    ('Air Jordan', '23', 'AJ23', 'aj23', 1, true),
    ('Air Jordan', '23', 'Jordan 23', 'jordan 23', 1, true),
    ('Air Jordan', '23', 'Jordan XXIII', 'jordan xxiii', 1, true),
    ('Air Jordan', '24', 'Air Jordan 24', 'air jordan 24', 1, true),
    ('Air Jordan', '24', 'AJ24', 'aj24', 1, true),
    ('Air Jordan', '24', 'Jordan 24', 'jordan 24', 1, true),
    ('Air Jordan', '24', 'Jordan XXIV', 'jordan xxiv', 1, true),
    ('Air Jordan', '25', 'Air Jordan 25', 'air jordan 25', 1, true),
    ('Air Jordan', '25', 'AJ25', 'aj25', 1, true),
    ('Air Jordan', '25', 'Jordan 25', 'jordan 25', 1, true),
    ('Air Jordan', '25', 'Jordan XXV', 'jordan xxv', 1, true),
    ('Air Jordan', '26', 'Air Jordan 26', 'air jordan 26', 1, true),
    ('Air Jordan', '26', 'AJ26', 'aj26', 1, true),
    ('Air Jordan', '26', 'Jordan 26', 'jordan 26', 1, true),
    ('Air Jordan', '26', 'Jordan XXVI', 'jordan xxvi', 1, true),
    ('Air Jordan', '27', 'Air Jordan 27', 'air jordan 27', 1, true),
    ('Air Jordan', '27', 'AJ27', 'aj27', 1, true),
    ('Air Jordan', '27', 'Jordan 27', 'jordan 27', 1, true),
    ('Air Jordan', '27', 'Jordan XXVII', 'jordan xxvii', 1, true),
    ('Air Jordan', '28', 'Air Jordan 28', 'air jordan 28', 1, true),
    ('Air Jordan', '28', 'AJ28', 'aj28', 1, true),
    ('Air Jordan', '28', 'Jordan 28', 'jordan 28', 1, true),
    ('Air Jordan', '28', 'Jordan XXVIII', 'jordan xxviii', 1, true),
    ('Air Jordan', '29', 'Air Jordan 29', 'air jordan 29', 1, true),
    ('Air Jordan', '29', 'AJ29', 'aj29', 1, true),
    ('Air Jordan', '29', 'Jordan 29', 'jordan 29', 1, true),
    ('Air Jordan', '29', 'Jordan XXIX', 'jordan xxix', 1, true),
    ('Air Jordan', '3', 'Air Jordan 3', 'air jordan 3', 1, true),
    ('Air Jordan', '3', 'AJ3', 'aj3', 1, true),
    ('Air Jordan', '3', 'Jordan 3', 'jordan 3', 1, true),
    ('Air Jordan', '3', 'Jordan III', 'jordan iii', 1, true),
    ('Air Jordan', '30', 'Air Jordan 30', 'air jordan 30', 1, true),
    ('Air Jordan', '30', 'AJ30', 'aj30', 1, true),
    ('Air Jordan', '30', 'Jordan 30', 'jordan 30', 1, true),
    ('Air Jordan', '30', 'Jordan XXX', 'jordan xxx', 1, true),
    ('Air Jordan', '31', 'Air Jordan 31', 'air jordan 31', 1, true),
    ('Air Jordan', '31', 'AJ31', 'aj31', 1, true),
    ('Air Jordan', '31', 'Jordan 31', 'jordan 31', 1, true),
    ('Air Jordan', '31', 'Jordan XXXI', 'jordan xxxi', 1, true),
    ('Air Jordan', '32', 'Air Jordan 32', 'air jordan 32', 1, true),
    ('Air Jordan', '32', 'AJ32', 'aj32', 1, true),
    ('Air Jordan', '32', 'Jordan 32', 'jordan 32', 1, true),
    ('Air Jordan', '32', 'Jordan XXXII', 'jordan xxxii', 1, true),
    ('Air Jordan', '33', 'Air Jordan 33', 'air jordan 33', 1, true),
    ('Air Jordan', '33', 'AJ33', 'aj33', 1, true),
    ('Air Jordan', '33', 'Jordan 33', 'jordan 33', 1, true),
    ('Air Jordan', '33', 'Jordan XXXIII', 'jordan xxxiii', 1, true),
    ('Air Jordan', '34', 'Air Jordan 34', 'air jordan 34', 1, true),
    ('Air Jordan', '34', 'AJ34', 'aj34', 1, true),
    ('Air Jordan', '34', 'Jordan 34', 'jordan 34', 1, true),
    ('Air Jordan', '34', 'Jordan XXXIV', 'jordan xxxiv', 1, true),
    ('Air Jordan', '35', 'Air Jordan 35', 'air jordan 35', 1, true),
    ('Air Jordan', '35', 'AJ35', 'aj35', 1, true),
    ('Air Jordan', '35', 'Jordan 35', 'jordan 35', 1, true),
    ('Air Jordan', '35', 'Jordan XXXV', 'jordan xxxv', 1, true),
    ('Air Jordan', '36', 'Air Jordan 36', 'air jordan 36', 1, true),
    ('Air Jordan', '36', 'AJ36', 'aj36', 1, true),
    ('Air Jordan', '36', 'Jordan 36', 'jordan 36', 1, true),
    ('Air Jordan', '36', 'Jordan XXXVI', 'jordan xxxvi', 1, true),
    ('Air Jordan', '37', 'Air Jordan 37', 'air jordan 37', 1, true),
    ('Air Jordan', '37', 'AJ37', 'aj37', 1, true),
    ('Air Jordan', '37', 'Jordan 37', 'jordan 37', 1, true),
    ('Air Jordan', '37', 'Jordan XXXVII', 'jordan xxxvii', 1, true),
    ('Air Jordan', '38', 'Air Jordan 38', 'air jordan 38', 1, true),
    ('Air Jordan', '38', 'AJ38', 'aj38', 1, true),
    ('Air Jordan', '38', 'Jordan 38', 'jordan 38', 1, true),
    ('Air Jordan', '38', 'Jordan XXXVIII', 'jordan xxxviii', 1, true),
    ('Air Jordan', '39', 'Air Jordan 39', 'air jordan 39', 1, true),
    ('Air Jordan', '39', 'AJ39', 'aj39', 1, true),
    ('Air Jordan', '39', 'Jordan 39', 'jordan 39', 1, true),
    ('Air Jordan', '39', 'Jordan XXXIX', 'jordan xxxix', 1, true),
    ('Air Jordan', '4', 'Air Jordan 4', 'air jordan 4', 1, true),
    ('Air Jordan', '4', 'AJ4', 'aj4', 1, true),
    ('Air Jordan', '4', 'Jordan 4', 'jordan 4', 1, true),
    ('Air Jordan', '4', 'Jordan IV', 'jordan iv', 1, true),
    ('Air Jordan', '40', 'Air Jordan 40', 'air jordan 40', 1, true),
    ('Air Jordan', '40', 'AJ40', 'aj40', 1, true),
    ('Air Jordan', '40', 'Jordan 40', 'jordan 40', 1, true),
    ('Air Jordan', '40', 'Jordan XL', 'jordan xl', 1, true),
    ('Air Jordan', '5', 'Air Jordan 5', 'air jordan 5', 1, true),
    ('Air Jordan', '5', 'AJ5', 'aj5', 1, true),
    ('Air Jordan', '5', 'Jordan 5', 'jordan 5', 1, true),
    ('Air Jordan', '5', 'Jordan V', 'jordan v', 1, true),
    ('Air Jordan', '6', 'Air Jordan 6', 'air jordan 6', 1, true),
    ('Air Jordan', '6', 'AJ6', 'aj6', 1, true),
    ('Air Jordan', '6', 'Jordan 6', 'jordan 6', 1, true),
    ('Air Jordan', '6', 'Jordan VI', 'jordan vi', 1, true),
    ('Air Jordan', '7', 'Air Jordan 7', 'air jordan 7', 1, true),
    ('Air Jordan', '7', 'AJ7', 'aj7', 1, true),
    ('Air Jordan', '7', 'Jordan 7', 'jordan 7', 1, true),
    ('Air Jordan', '7', 'Jordan VII', 'jordan vii', 1, true),
    ('Air Jordan', '8', 'Air Jordan 8', 'air jordan 8', 1, true),
    ('Air Jordan', '8', 'AJ8', 'aj8', 1, true),
    ('Air Jordan', '8', 'Jordan 8', 'jordan 8', 1, true),
    ('Air Jordan', '8', 'Jordan VIII', 'jordan viii', 1, true),
    ('Air Jordan', '9', 'Air Jordan 9', 'air jordan 9', 1, true),
    ('Air Jordan', '9', 'AJ9', 'aj9', 1, true),
    ('Air Jordan', '9', 'Jordan 9', 'jordan 9', 1, true),
    ('Air Jordan', '9', 'Jordan IX', 'jordan ix', 1, true),
    ('ASICS', 'GEL-Kayano 14', 'Gel Kayano 14', 'gel kayano 14', 5, true),
    ('ASICS', 'GEL-Kayano 14', 'Kayano 14', 'kayano 14', 5, true),
    ('Gucci', 'GG Supreme', 'GG Supreme', 'gg supreme', 10, true),
    ('Gucci', 'GG Supreme', 'GG Supreme Canvas', 'gg supreme canvas', 6, true),
    ('New Balance', '990v6', '990 v6', '990 v6', 2, true),
    ('Nike', 'Air Foamposite', 'Foamposite', 'foamposite', 1, true),
    ('Nike', 'Air Force 1', 'AF1', 'af1', 10, true),
    ('Nike', 'Air Force 1', 'Air Force', 'air force', 5, true),
    ('Nike', 'Air Force 1', 'Air Force One', 'air force one', 5, true),
    ('Nike', 'Air Force 1', 'Airforce', 'airforce', 5, true),
    ('Nike', 'Air More Uptempo', 'Air More Uptempo', 'air more uptempo', 10, true),
    ('Nike', 'Air More Uptempo', 'More Uptempo', 'more uptempo', 5, true),
    ('Nike', 'Air More Uptempo', 'Uptempo', 'uptempo', 2, true),
    ('Nike', 'Dunk Low', 'Dunk', 'dunk', 1, true),
    ('Nike', 'Kobe', 'Kobe 6', 'kobe 6', 8, true),
    ('Nike', 'Kobe', 'Kobe 6 Protro', 'kobe 6 protro', 10, true),
    ('Nike', 'Kobe', 'Kobe VI', 'kobe vi', 8, true),
    ('Nike', 'Kobe', 'Kobe VI Protro', 'kobe vi protro', 10, true),
    ('Nike', 'Kobe', 'Nike Kobe', 'nike kobe', 1, true),
    ('Nike', 'Kobe', 'Zoom Kobe', 'zoom kobe', 5, true),
    ('Nike', 'P-6000', 'P6000', 'p6000', 1, true),
    ('Off-White', 'Out Of Office', 'OOO', 'ooo', 1, true)
) as seed(brand_label, model_label, alias_label, alias_normalized, priority, is_active)
join public.tag_brands brand
  on brand.tenant_id is null and lower(brand.canonical_label) = lower(seed.brand_label)
join public.tag_models model
  on model.brand_id = brand.id and model.tenant_id is null and lower(model.canonical_label) = lower(seed.model_label)
where not exists (
  select 1 from public.tag_aliases alias
  where alias.tenant_id is null
    and alias.entity_type = 'model'
    and alias.alias_normalized = seed.alias_normalized
);

insert into public.tag_sizes (tenant_id, size_type, canonical_label, sort_order)
select null, seed.size_type, seed.label, seed.sort_order
from (
  values
    ('none', 'OS', 0),
    ('custom', 'OS', 0),
    ('clothing', 'XXS', 10), ('clothing', 'XS', 20),
    ('clothing', 'SMALL', 30), ('clothing', 'MEDIUM', 40),
    ('clothing', 'LARGE', 50), ('clothing', 'XL', 60),
    ('clothing', '2XL', 70), ('clothing', '3XL', 80),
    ('clothing', '28', 100), ('clothing', '29', 110),
    ('clothing', '30', 120), ('clothing', '31', 130),
    ('clothing', '32', 140), ('clothing', '33', 150),
    ('clothing', '34', 160), ('clothing', '36', 170),
    ('clothing', '38', 180), ('clothing', '40', 190),
    ('shoe', '3.5Y / 5W', 10), ('shoe', '4Y / 5.5W', 20),
    ('shoe', '4.5Y / 6W', 30), ('shoe', '5Y / 6.5W', 40),
    ('shoe', '5.5Y / 7W', 50), ('shoe', '6Y / 7.5W', 60),
    ('shoe', '6.5Y / 8W', 70), ('shoe', '7Y / 8.5W', 80),
    ('shoe', '7.5M / 9W', 90), ('shoe', '8M / 9.5W', 100),
    ('shoe', '8.5M / 10W', 110), ('shoe', '9M / 10.5W', 120),
    ('shoe', '9.5M / 11W', 130), ('shoe', '10M / 11.5W', 140),
    ('shoe', '10.5M / 12W', 150), ('shoe', '11M / 12.5W', 160),
    ('shoe', '11.5M / 13W', 170), ('shoe', '12M / 13.5W', 180),
    ('shoe', '12.5M / 14W', 190), ('shoe', '13M / 14.5W', 200),
    ('shoe', '13.5M / 15W', 210), ('shoe', '14M / 15.5W', 220),
    ('shoe', '15M / 16.5W', 230),
    ('shoe', 'EU 35 (US 5.5W)', 300), ('shoe', 'EU 36 (US 6W)', 310),
    ('shoe', 'EU 36.5 (US 6.5W)', 320), ('shoe', 'EU 37 (US 7W)', 330),
    ('shoe', 'EU 37.5 (US 7.5W)', 340), ('shoe', 'EU 38 (US 8W)', 350),
    ('shoe', 'EU 38.5 (US 8.5W)', 360), ('shoe', 'EU 39 (US 7M)', 370),
    ('shoe', 'EU 39.5 (US 7M)', 380), ('shoe', 'EU 40 (US 7M)', 390),
    ('shoe', 'EU 40 (US 8M)', 400), ('shoe', 'EU 41 (US 8.5M)', 410),
    ('shoe', 'EU 42 (US 9M)', 420), ('shoe', 'EU 43 (US 10M)', 430),
    ('shoe', 'EU 44 (US 11M)', 440), ('shoe', 'EU 45 (US 12M)', 450),
    ('shoe', 'EU 46 (US 13M)', 460), ('shoe', 'EU 47 (US 14M)', 470),
    ('shoe', 'EU 48 (US 15M)', 480), ('shoe', 'EU 49 (US 16M)', 490)
) as seed(size_type, label, sort_order)
where not exists (
  select 1 from public.tag_sizes size
  where size.tenant_id is null
    and size.size_type = seed.size_type
    and lower(size.canonical_label) = lower(seed.label)
);

commit;
